### PR TITLE
Routes n status

### PR DESCRIPTION
**Pull request by Dragoshiz**

### CODE REVIEW

**Review by pandaero — APPROVED** [review]
looks good

**Review by Alohakaloha — APPROVED** [review]
approved

**Review by pandaero — APPROVED** [review]
Approved

**Review by pandaero — APPROVED** [review]
Seen all the files and approved

**Review by Alohakaloha — APPROVED** [review]

**Comment by Dragoshiz** [comment]
something does not work

**Review by pandaero — APPROVED** [review]
reviewed approved

**Comment by pandaero** [comment]
image

Do I have write access?

**Comment by Alohakaloha** [comment]
@pandaero did you get the invite as collaborator

**Pull request merged**
